### ISSUE TITLE
Wiping files' history

### ISSUE THREAD

**Issue by serrq** [roozbehzarei/filester#24] opened 2022-09-30 11:33 UTC
There is no way to wipe files' history.

![Screenshot_2022-09-30-13-31-28-63_b52257a2dc2f0362f8c2187ecbe4cebf (1)](https://user-images.githubusercontent.com/113377431/193260762-30016c9b-676d-4d7a-b071-f42c3fbdcffe.jpg)

**Comment by roozbehzarei** [comment] 2022-09-30 12:19
This is a duplicate of #12 which is on the roadmap of the next release. You can check the progress [here](https://github.com/roozbehzarei/filester/projects/3).

**Closed as completed by roozbehzarei** 2022-09-30 12:19 UTC
