### ISSUE TITLE
Delete Links Older than 14 days

### ISSUE THREAD

**Issue by adhiraj-ranjan** [roozbehzarei/filester#31] opened 2023-07-30 16:15 UTC
Since the uploaded files are available for 14 days on the server, Whyn't give an option for deleting links older than 14 days, Or auto deleting invalid ( older than 14 days ) links.
This would be good, since you will know, What links have expired and what are still active

**Comment by roozbehzarei** [comment] 2023-07-30 16:27
This is a duplicate of #12 and on roadmap for the next release.

**Closed by roozbehzarei** 2023-07-30 16:27 UTC
