### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by CodeCubeNeo** [roozbehzarei/filester#18] opened 2022-09-07 18:39 UTC
Just asking, nothing more.

**Comment by roozbehzarei** [comment] 2022-09-07 19:10
Of couse, I've solved some issues already and working on the rest. Next version will be released this weekend (or next weekend worst case scenario).

**Comment by CodeCubeNeo** [comment] 2022-09-07 20:52
Awesome. Really looking forward for the next release.

**Comment by roozbehzarei** [comment] 2022-09-16 00:23
New update released. You can now download it from Releases section here on GitHub and it soon will be available on F-Droid store.

**Closed by roozbehzarei** 2022-09-16 00:23 UTC

**Comment by CodeCubeNeo** [comment] 2022-10-22 09:08
Hello. Same queation. Sorry for bothering you, but it is a really cool app for sharing something quiclky and if it stays on the internet for 14 days it is not very pracfical.

**Comment by roozbehzarei** [comment] 2022-10-23 19:33
> Hello. Same queation. Sorry for bothering you, but it is a really cool app for sharing something quiclky and if it stays on the internet for 14 days it is not very pracfical.

Unfortunately I couldn't find any reliable hosts that store the files indefinitely. Let me know if you know any.

**Comment by CodeCubeNeo** [comment] 2022-10-23 20:11
No, i meant in reference to my option do delete request (https://github.com/roozbehzarei/filester/issues/12). Meaning for less then 14 days

**Comment by roozbehzarei** [comment] 2022-10-24 05:30
Oh, right. It's on the roadmap for the next release. The problem is I'm currently working on a full-time job, therefore it might take some time before I release the new version.

**Comment by CodeCubeNeo** [comment] 2023-01-27 21:37
Hi. I am very grateful for this app.
